language: node_js
node_js:
  - "11"
install:
  - yarn --ignore-engines
  - yarn build
deploy:
  - yarn build
  provider: surge
  project: ./dist/
  domain: trustedreviews.surge.sh
  skip-cleanup: true
